config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :tweets do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # validates :sweetness, presence: true
  # validates :bitter, presence: true
  # validates :acidity, presence: true
  # validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @tweets = Tweet.all
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  end

  def new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      flash.now[:alert] =  '必須を入力してください。'
      render :new
    end
  end

  def show
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def tweet_params
    params.permit(:sweetness, :bitter, :acidity, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NewApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .notification
      - flash.each do |key, value|
        = content_tag :div, value, class: key
    = yield

app/views/top/_chart.html.haml
%canvas#myChart
:javascript
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'polarArea',
    data: {
      labels: ["甘み", "酸味", "苦味", "コク"],
      datasets: [{
          backgroundColor: [
              "#FF1493", //ディープピンク
              "#FFD700", //ゴールド
              "#A68C26", //レッド
              "#800080", //パープル
          ],
        data: [80, 90, 60, 70]
      }],
    }
  });

app/views/top/index.html.haml
.head 
  =link_to "珈琲app", root_path

.household-account-book__registration 
%ul
  %li
    = link_to "記録する", tweets_path
  %li
    = link_to "なんかする", root_path
  %li
    = link_to "ふざける", root_path

.graph
  = render "top/chart"

.contents.row
  - @tweets.each do |tweet|
    = render partial: "chart", locals: { tweet: tweet }
  -# = paginate(@tweets)

app/views/tweets/create.html.haml
= link_to "OK", root_path

app/views/tweets/index.html.haml
.household-account-book
  = link_to "トップへ戻る",root_path

.household-account-book__registration
%ul
  %li
    = link_to "珈琲部", root_path
  %li
    = link_to "ドリップ", new_tweet_path
  %li
    = link_to "珈琲のばん", root_path

app/views/tweets/new.html.haml
.taste-form
  .taste-form__header 味の記録
  = form_with model: @tweet, url: tweets_path, class: "tweets-form", method: :post, local:true do |f|
    .taste-content
      .taste-content__form-group
        %label
          甘み
          %span.form-require 
        = f.text_field :sweetness, class: "income-textfield-default", value: ""
      .taste-content__form-group
        %label
          酸味
          %span.form-require 
        = f.text_field :bitter, class: "income-textfield-default", value: ""
      .taste-content__form-group
        %label
          苦味
          %span.form-require 
        = f.text_field :acidity, class: "income-textfield-default", value: ""
      .taste-content__form-group
        %label
          コク
          %span.form-require 
        = f.text_field :body, class: "income-textfield-default", value: ""
      = f.submit "登録する", class: "btn-default"
      = link_to "TOPへもどる", "#", class: "back-btn"